### ISSUE TITLE
Long name on Water tile

### ISSUE THREAD

**Issue by Jacklz** [Jadams505/Twaila#12]
Is this a localization issue?
![Capture](https://github.com/Jadams505/Twaila/assets/5264573/690e58d8-f16e-471a-be0a-561be0e5df2e)

**Comment by Jadams505** [comment]
Yes that is a localization issue. I have noticed a few tiles that have bad localization keys, so I'll add this one to the list. I plan on doing an exhaustive search and fixing all of them at the same time.

**Comment by Jadams505** [comment]
Fixed with v0.4.0.4
