### ISSUE TITLE
Issue with NPCS

### ISSUE THREAD

**Issue by BogdanFalk** [Jadams505/Twaila#14]
![image](https://github.com/Jadams505/Twaila/assets/30993234/6da66b55-d1b5-45c7-9cb3-31b28af93c5a)
Seems to be an issue where NPCs are in the wrong place when you scroll over them my mouse is underground and the NPC is on the otherside of the screen, but they are like shifted there so every single npc is around that area just shifted down to the right

Mods List if it helps:
Boss Checklist v1.6.2
Calamity Mod v2.0.3.2
Which Mod is This From? (WMITF) v2.7.0
Thorium Mod v1.7.1.1
LuiAFK Reborn v1.2
Lights And Shadow v1.2.3
Twaila v0.5.0.0
Magic Storage v0.6.0.2
Calamity's Vanities v11.0.6
Advanced World Generation v3.1.3
Recipe Browser v0.10.1.5
Fargo's Mutant Mod v3.0
Quality of Life v1.6.5.2
absoluteAquarian Utilities v1.0.4.1
HERO's Mod v0.4.12.6
Census - Town NPC Checklist v0.5.2.2
AlchemistNPC Lite v1.9
Useful NPCs v3.0.2
Wing Slot Extra v1.3.6
Teleport to pylons from anywhere! v0.6.2
Ore Excavator v0.8.5
Bosses As NPCs v0.2.4

Settings:
Resolution: 2560x1377 (Borderless Window: Enabled) (Windowed)
Zoom: 100% (133%)

Thanks for the work!

**Comment by Jadams505** [comment]
Thanks for the report. My guess is that it has to do with zoom. Do you encounter this issue at zoom 100%?

**Comment by BogdanFalk** [comment]
Yes I even tried different resolutions, fullscreen/windowed as well, on all of them and all zoom levels is the same.

**Comment by Jadams505** [comment]
Hopefully I fixed the issue with v0.5.0.1. Please let me know if the issue persists.

**Comment by BogdanFalk** [comment]
Works fine now!
Thank you for your work ❤️
