### ISSUE TITLE
[Suggestion] TWAILA UI goes transparent when hovered

### ISSUE THREAD

**Issue by Agent3554** [Jadams505/Twaila#3]
As the title says, does something similar to Boss Health Bar mod when you hover a mouse over it

Other suggestion
- Configurable transparency/opacity when you hover on the UI itself
- Configurable transparency/opacity of UI itself without the need to hover over it
- Toggle option to make hover-over UI work, or change transparency without hovering over the UI

**Comment by Jadams505** [comment]
Thank you for the suggestion this has been added with v0.3.1.0. You can adjust HoverOpacity to your liking.
